image: node:20.10.0

definitions:
  caches:
    npm: ~/.npm

pipelines:
  default:
    - step:
        name: Build app
        deployment: test
        caches:
          - npm
        script:
          - npm ci
          - npx expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
          - npx eas-cli build --platform android --non-interactive --no-wait
