title: Ieatta Help
tagline: Ieatta Help - all your Ieatta questions answered in one place.
description: Got a question about receipts, expenses, corporate cards, or anything else in the spend management universe? Get answers at help.ieatta.com.
url: https://help.ieatta.com
author: Ieatta
logo: /assets/images/ieatta-help.svg
repository: Ieatta/App
open_url: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: /assets/images/og-preview-image.png

exclude: [README.md, TEMPLATE.md, vendor]

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
